"""Tests for DOCX export -- basic and professional report modes."""

import pytest

from distill.docx_export import (
    _add_formatted_text,
    _extract_title,
    _strip_front_matter,
    export_report,
    markdown_to_docx,
)


@pytest.fixture
def sample_md(tmp_path):
    """Create a sample markdown file."""
    content = """# Strategic Intelligence Report: AI

*Topic: ai | March 9, 2026*
*1 channel(s), 50 videos analyzed | Accordion method*

---

## Table of Contents

1. **Executive Briefing** (1,200 words)
2. **Tech Landscape** (800 words)

---

## Executive Briefing

The AI landscape shifted dramatically. **Microsoft** announced new pricing.
Key finding: [Confirmed] enterprise adoption accelerated 40%.

- Bullet one with **bold text**
- Bullet two with `inline code`

## Tech Landscape

Several [Reported] developments changed the picture.

1. First numbered item
2. Second numbered item

### Sub-heading Here

More content with *italic text* and [a link](https://example.com).

---

*Total: 2,000 words | 2 sections | Generated by Distill*
"""
    md_path = tmp_path / "report.md"
    md_path.write_text(content, encoding="utf-8")
    return md_path


class TestExtractTitle:
    def test_extracts_h1(self):
        assert _extract_title("# Hello World\n## Sub") == "Hello World"

    def test_skips_h2(self):
        assert _extract_title("## Not This\n# This One") == "This One"

    def test_returns_none_for_no_h1(self):
        assert _extract_title("## Only H2\nNo headings") is None

    def test_strips_whitespace(self):
        assert _extract_title("#   Spaced Title  \n") == "Spaced Title"


class TestStripFrontMatter:
    def test_strips_h1_title(self):
        result = _strip_front_matter("# Title\n\n## Section 1\nContent")
        assert "# Title" not in result
        assert "## Section 1" in result

    def test_strips_metadata_lines(self):
        result = _strip_front_matter("# Title\n*metadata line*\n\n## Section")
        assert "metadata line" not in result
        assert "## Section" in result

    def test_strips_toc_section(self):
        content = "# Title\n\n## Table of Contents\n1. Exec\n2. Landscape\n\n---\n\n## Executive Briefing\nContent"
        result = _strip_front_matter(content)
        assert "Table of Contents" not in result
        assert "Executive Briefing" in result

    def test_preserves_regular_bold(self):
        result = _strip_front_matter("# Title\n\n**Bold text** here")
        assert "**Bold text**" in result


class TestMarkdownToDocx:
    def test_creates_file(self, sample_md, tmp_path):
        out = tmp_path / "output.docx"
        result = markdown_to_docx(sample_md, docx_path=out)
        assert result.exists()
        assert result.stat().st_size > 0

    def test_default_path(self, sample_md):
        result = markdown_to_docx(sample_md)
        assert result.suffix == ".docx"
        assert result.exists()
        result.unlink()  # cleanup

    def test_custom_title(self, sample_md, tmp_path):
        out = tmp_path / "custom.docx"
        result = markdown_to_docx(sample_md, docx_path=out, title="Custom Title")
        assert result.exists()


class TestExportReport:
    def test_creates_professional_report(self, sample_md, tmp_path):
        out = tmp_path / "report.docx"
        result = export_report(sample_md, docx_path=out, title="Test Report")
        assert result.exists()
        assert result.stat().st_size > 0

    def test_larger_than_basic(self, sample_md, tmp_path):
        basic = tmp_path / "basic.docx"
        pro = tmp_path / "pro.docx"
        markdown_to_docx(sample_md, docx_path=basic)
        export_report(sample_md, docx_path=pro, title="Pro Report")
        # Professional version should be larger (cover page, TOC, etc.)
        assert pro.stat().st_size >= basic.stat().st_size * 0.8  # allow some variance

    def test_default_path(self, sample_md):
        result = export_report(sample_md)
        assert result.suffix == ".docx"
        assert result.exists()
        result.unlink()  # cleanup


class TestConfidenceBadges:
    def test_confirmed_badge(self, tmp_path):
        """Test that confidence badges are recognized in formatted text."""
        from docx import Document

        doc = Document()
        para = doc.add_paragraph()
        _add_formatted_text(para, "This is [Confirmed] true and [Speculated] maybe")
        # Should have multiple runs (text + badge + text + badge + text)
        assert len(para.runs) >= 4

    def test_mixed_formatting(self, tmp_path):
        from docx import Document

        doc = Document()
        para = doc.add_paragraph()
        _add_formatted_text(para, "**Bold** then [Reported] then `code`")
        assert len(para.runs) >= 5
